# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

melsi_permanova_f <- function(Xt, group, k) {
    .Call(`_MeLSI_melsi_permanova_f`, Xt, group, k)
}

