name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  R-CMD-check:
    name: Bioc devel (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: devel

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1

      - name: Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1

      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'error'

      - name: Upload check output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}-Rcheck
          path: |
            ${{ steps.build-install-check.outputs.check-dir }}
